version: '3'

services:
  react:
    build: .
    volumes:
      - "./react:/app"
    ports:
      - "80:3000"
    depends_on:
      - api

  api:
    build: .
    volumes:
      - "./server:/app"
    ports:
      - "3030:3030"